In [1]:
print("hello world")

hello world


### Question 1
Given the following numpy array:

```python
arr = np.array([1, 2, 3, 4, 5])
```
Write a Python code to multiply each element in the array by 2.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_2x = 2 * arr
arr_2x

array([ 2,  4,  6,  8, 10])

### Question 2

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to select the second row of the array.


In [16]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row2 = arr[1]
row2

array([4, 5, 6])

### Question 3

Create a 2D numpy array of shape (5, 5) filled with the number 1.

In [8]:
import numpy as np
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Question 4

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to calculate the sum of all the elements in each row.


In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_arr_by_row = np.sum(arr, axis=1)
sum_arr_by_row

array([ 6, 15, 24])

### Question 5

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to calculate the average of all the elements.

In [15]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
all_avg = np.mean(arr)
all_avg

5.0